config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :articles
  resources :users do 
  	resources :projects
  end
  get '/projets', to: 'projects#edito'
  root to: "home#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Linkedin login / register
  def self.connect_to_linkedin(auth, signed_in_resource=nil) 
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user 
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user 
        return registered_user 
      else 
        user = User.create(name:auth.info.nickname, provider:auth.provider, uid:auth.uid, email:auth.info.email, headline: auth.info.headline, image: auth.info.image, location: auth.info.location, url: auth.info.urls.public_profile, password:Devise.friendly_token[0,20], )
      end 
    end 
  end

  def is_current_user?
    if self === current_user
      return true
    else 
      return false
    end
  end

  # def user_infos_linkedin
  #   profile = Linkedin::Profile.new(self.url)
  #   return profile
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include EmojiHelper
	def home
		
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController 
   def linkedin 
     auth = env["omniauth.auth"] 
     @user = User.connect_to_linkedin(request.env["omniauth.auth"],current_user) 
     if @user.persisted? 
       flash[:notice] = I18n.t "devise.omniauth_callbacks.success" 
       sign_in_and_redirect @user, :event => :authentication 
     else 
       session["devise.linkedin_uid"] = request.env["omniauth.auth"] 
       redirect_to new_user_registration_url 
     end
    end
 end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def edito

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/:id.:format
  def show
    
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass_sign_in => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email, :headline, :type_user, :location ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/home.html.erb
<div class="container-fluid LeGarage-homepage">
	<div class="LeGarage-homepage--banner">
		<h1> Marketplace entre des CTO et des porteurs de projet </h1>
		<p> Nous souhaitons mettre en contact des personnes qui ont un projet et des tech capable de les réaliser<br>Relançons le mythe du "garage"!</p>
		<p class="moji"><%= Emoji.find_by_alias("rocket").raw %></p>
		<button class="LeGarage--button LeGarage--button-default"> Voir les projets </button>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<header class="container-fluid LeGarage-header">
	<div class="container">
		<%= link_to 'Le Garage', root_path, class: 'LeGarage-header--logo' %>
		<div class="LeGarage-header--menu">
			<a href="#"> Accueil </a>
			<a href="#"> Le concept </a>
			<a href="#"> Qui sommes-nous ? </a>
			<%= link_to 'Projets', projets_path %>
			<% if user_signed_in? %>

				<%= link_to current_user.name, user_path(current_user) %>
				<%= link_to 'Deconnexion', destroy_user_session_path, method: :delete %>				
				<img src="<%= current_user.image %>" alt="profile image" class="LeGarage-header--avatar">
			<% else %>
				<%= link_to "Connexion avec Linkedin", user_linkedin_omniauth_authorize_path %>
			<% end %>
		</div>
	</div>
</header>

app/views/layouts/_navigation_application.html.erb
<header class="container-fluid LeGarage-header--secondary">
	<div class="container">
		<%= link_to 'Le Garage', root_path, class: 'LeGarage-header--logo' %>
		<div class="LeGarage-header--menu">
			<%= link_to 'Accueil', root_path %>
			<a href="#"> Le concept </a>
			<a href="#"> Qui sommes-nous ? </a>
			<a href="#"> Projets </a>
			<% if user_signed_in? %>
				<%= link_to current_user.name, user_path(current_user) %>
				<%= link_to 'Deconnexion', destroy_user_session_path, method: :delete %>				
				<img src="<%= current_user.image %>" alt="profile image" class="LeGarage-header--avatar">
			<% else %>
				<%= link_to "Connexion avec Linkedin", user_linkedin_omniauth_authorize_path %>
			<% end %>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeGarage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
  </head>

  <body>
    <% if controller_name == "home" && action_name = "home" %>
  	 <%= render partial: 'layouts/navigation' %>
    <% else %>
      <%= render partial: 'layouts/navigation_application' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/edito.html.erb
<div class="container-fluid LeGarage-project">
	<div class="col-md-12 LeGarage-project--subheader">
		<h1> Welcome toi ! </h1>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid LeGarage-user">
	<div class="container">
		<%= form_for @user, html: { class: 'form-horizontal' } do |f| %>
			<div class="form-group">
				<label> Email </label>
				<%= f.email_field :email, class: 'form-control' %>
			</div>
			<div class="form-group">
				<label> Name </label>
				<%= f.text_field :name, class: 'form-control' %>
			</div>
			<div class="form-group">
				<label> Description </label>
				<%= f.text_field :headline, class: 'form-control' %>
			</div>
			<div class="form-group">
				<label> Location </label>
				<%= f.text_field :location, class: 'form-control' %>
			</div>
			<div class="form-group">
				<label> CTO ou Porteur de projet </label>
				<%= label :type_user, 'CTO' %>
				<%= f.radio_button :type_user, 'CTO', :checked => true %>
				<%= label :type_user, 'Porteur de projet' %>
				<%= f.radio_button :type_user, 'project' %>
			</div>
			<div class="form-group">
				<%= f.submit 'Envoyer', class: 'LeGarage--button-default LeGarage--button' %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid LeGarage-user">
	<div class="container">
		<% if current_user.type_user === nil %>
			<div class="LeGarage-user--warning">
				Vous n'avez pas encore renseigné si vous êtes un CTO ou un porteur de projet, <%= link_to 'Faites le maintenant', edit_user_path(@user), class: 'LeGarage--special-link' %>
			</div>
		<% end %>
		<div class="col-md-3">
			<div class="col-md-12 LeGarage-user--sidebar">
				<h3> <%= @user.name %> </h3>
				<p> <%= @user.location %> </p>
				<p> <%= @user.headline %> </p>
				<p class="LeGarage-user--badge"><%= @user.type_user %></p>
			</div>
			<% if @user === current_user %>
				<%= link_to 'Éditer mon profile', edit_user_path(@user), class: 'col-md-12 LeGarage--button-default LeGarage--button LeGarage--button-user--modify' %>
				<%= link_to 'Supprimer mon compte', user_path(@user), method: :delete, class: 'col-md-12 LeGarage--button-default LeGarage--button LeGarage--button-user' %>
			<% end %>
		</div>
		<div class="col-md-9">

		</div>
	</div>
</div>